type allCountriesType = {
  continent: string;
  countries: string[];
};

export const allCountries: allCountriesType[] = [
  {
    continent: "All Countries",
    countries: [
      "Algeria",
      "Angola",
      "Benin",
      "Botswana",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Cameroon",
      "Central African Republic",
      "Chad",
      "Comoros",
      "Congo",
      "Côte d'Ivoire",
      "DRC",
      "Djibouti",
      "Egypt",
      "Equatorial Guinea",
      "Eritrea",
      "Ethiopia",
      "Gabon",
      "Gambia",
      "Ghana",
      "Guinea",
      "Guinea-Bissau",
      "Kenya",
      "Lesotho",
      "Liberia",
      "Libyan Arab Jamahiriya",
      "Madagascar",
      "Malawi",
      "Mali",
      "Mauritania",
      "Mauritius",
      "Mayotte",
      "Morocco",
      "Mozambique",
      "Namibia",
      "Niger",
      "Nigeria",
      "Rwanda",
      "Réunion",
      "Saint Helena",
      "Sao Tome and Principe",
      "Senegal",
      "Seychelles",
      "Sierra Leone",
      "Somalia",
      "South Africa",
      "South Sudan",
      "Sudan",
      "Swaziland",
      "Tanzania",
      "Togo",
      "Tunisia",
      "Uganda",
      "Western Sahara",
      "Zambia",
      "Zimbabwe",
      "Australia",
      "Cook Islands",
      "Fiji",
      "French Polynesia",
      "Kiribati",
      "Marshall Islands",
      "Micronesia",
      "Nauru",
      "New Caledonia",
      "New Zealand",
      "Niue",
      "Palau",
      "Papua New Guinea",
      "Samoa",
      "Solomon Islands",
      "Tokelau",
      "Tonga",
      "Tuvalu",
      "Vanuatu",
      "Wallis and Futuna",
      "Argentina",
      "Bolivia",
      "Brazil",
      "Chile",
      "Colombia",
      "Ecuador",
      "Falkland Islands (Malvinas)",
      "French Guiana",
      "Guyana",
      "Paraguay",
      "Peru",
      "Suriname",
      "Uruguay",
      "Venezuela",
      "Anguilla",
      "Antigua and Barbuda",
      "Aruba",
      "Bahamas",
      "Barbados",
      "Belize",
      "Bermuda",
      "British Virgin Islands",
      "Canada",
      "Caribbean Netherlands",
      "Cayman Islands",
      "Costa Rica",
      "Cuba",
      "Curaçao",
      "Dominica",
      "Dominican Republic",
      "El Salvador",
      "Greenland",
      "Grenada",
      "Guadeloupe",
      "Guatemala",
      "Haiti",
      "Honduras",
      "Jamaica",
      "Martinique",
      "Mexico",
      "Montserrat",
      "Nicaragua",
      "Panama",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Martin",
      "Saint Pierre Miquelon",
      "Saint Vincent and the Grenadines",
      "Sint Maarten",
      "St. Barth",
      "Trinidad and Tobago",
      "Turks and Caicos Islands",
      "USA",
      "Afghanistan",
      "Armenia",
      "Azerbaijan",
      "Bahrain",
      "Bangladesh",
      "Bhutan",
      "Brunei",
      "Cambodia",
      "China",
      "Cyprus",
      "Georgia",
      "Hong Kong",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Israel",
      "Japan",
      "Jordan",
      "Kazakhstan",
      "Kuwait",
      "Kyrgyzstan",
      "Lao People's Democratic Republic",
      "Lebanon",
      "Macao",
      "Malaysia",
      "Maldives",
      "Mongolia",
      "Myanmar",
      "N. Korea",
      "Nepal",
      "Oman",
      "Pakistan",
      "Palestine",
      "Philippines",
      "Qatar",
      "S. Korea",
      "Saudi Arabia",
      "Singapore",
      "Sri Lanka",
      "Syrian Arab Republic",
      "Taiwan",
      "Tajikistan",
      "Thailand",
      "Timor-Leste",
      "Turkey",
      "UAE",
      "Uzbekistan",
      "Vietnam",
      "Yemen",
      "Albania",
      "Andorra",
      "Austria",
      "Belarus",
      "Belgium",
      "Bosnia",
      "Bulgaria",
      "Channel Islands",
      "Croatia",
      "Czechia",
      "Denmark",
      "Estonia",
      "Faroe Islands",
      "Finland",
      "France",
      "Germany",
      "Gibraltar",
      "Greece",
      "Holy See (Vatican City State)",
      "Hungary",
      "Iceland",
      "Ireland",
      "Isle of Man",
      "Italy",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Macedonia",
      "Malta",
      "Moldova",
      "Monaco",
      "Montenegro",
      "Netherlands",
      "Norway",
      "Poland",
      "Portugal",
      "Romania",
      "Russia",
      "San Marino",
      "Serbia",
      "Slovakia",
      "Slovenia",
      "Spain",
      "Sweden",
      "Switzerland",
      "UK",
      "Ukraine",
    ],
  },
];

// export const allCountries: allCountriesType[] = [
//   {
//     continent: "All Countries",
//     countries: [
//       "Algeria",
//       "Angola",
//       "Benin",
//       "Botswana",
//       "Burkina Faso",
//       "Burundi",
//       "Cabo Verde",
//       "Cameroon",
//       "Central African Republic",
//       "Chad",
//       "Comoros",
//       "Congo",
//       "Côte d'Ivoire",
//       "DRC",
//       "Djibouti",
//       "Egypt",
//       "Equatorial Guinea",
//       "Eritrea",
//       "Ethiopia",
//       "Gabon",
//       "Gambia",
//       "Ghana",
//       "Guinea",
//       "Guinea-Bissau",
//       "Kenya",
//       "Lesotho",
//       "Liberia",
//       "Libyan Arab Jamahiriya",
//       "Madagascar",
//       "Malawi",
//       "Mali",
//       "Mauritania",
//       "Mauritius",
//       "Mayotte",
//       "Morocco",
//       "Mozambique",
//       "Namibia",
//       "Niger",
//       "Nigeria",
//       "Rwanda",
//       "Réunion",
//       "Saint Helena",
//       "Sao Tome and Principe",
//       "Senegal",
//       "Seychelles",
//       "Sierra Leone",
//       "Somalia",
//       "South Africa",
//       "South Sudan",
//       "Sudan",
//       "Swaziland",
//       "Tanzania",
//       "Togo",
//       "Tunisia",
//       "Uganda",
//       "Western Sahara",
//       "Zambia",
//       "Zimbabwe",
//       "Australia",
//       "Cook Islands",
//       "Fiji",
//       "French Polynesia",
//       "Kiribati",
//       "Marshall Islands",
//       "Micronesia",
//       "Nauru",
//       "New Caledonia",
//       "New Zealand",
//       "Niue",
//       "Palau",
//       "Papua New Guinea",
//       "Samoa",
//       "Solomon Islands",
//       "Tokelau",
//       "Tonga",
//       "Tuvalu",
//       "Vanuatu",
//       "Wallis and Futuna",
//       "Argentina",
//       "Bolivia",
//       "Brazil",
//       "Chile",
//       "Colombia",
//       "Ecuador",
//       "Falkland Islands (Malvinas)",
//       "French Guiana",
//       "Guyana",
//       "Paraguay",
//       "Peru",
//       "Suriname",
//       "Uruguay",
//       "Venezuela",
//       "Anguilla",
//       "Antigua and Barbuda",
//       "Aruba",
//       "Bahamas",
//       "Barbados",
//       "Belize",
//       "Bermuda",
//       "British Virgin Islands",
//       "Canada",
//       "Caribbean Netherlands",
//       "Cayman Islands",
//       "Costa Rica",
//       "Cuba",
//       "Curaçao",
//       "Dominica",
//       "Dominican Republic",
//       "El Salvador",
//       "Greenland",
//       "Grenada",
//       "Guadeloupe",
//       "Guatemala",
//       "Haiti",
//       "Honduras",
//       "Jamaica",
//       "Martinique",
//       "Mexico",
//       "Montserrat",
//       "Nicaragua",
//       "Panama",
//       "Saint Kitts and Nevis",
//       "Saint Lucia",
//       "Saint Martin",
//       "Saint Pierre Miquelon",
//       "Saint Vincent and the Grenadines",
//       "Sint Maarten",
//       "St. Barth",
//       "Trinidad and Tobago",
//       "Turks and Caicos Islands",
//       "USA",
//       "Afghanistan",
//       "Armenia",
//       "Azerbaijan",
//       "Bahrain",
//       "Bangladesh",
//       "Bhutan",
//       "Brunei",
//       "Cambodia",
//       "China",
//       "Cyprus",
//       "Georgia",
//       "Hong Kong",
//       "India",
//       "Indonesia",
//       "Iran",
//       "Iraq",
//       "Israel",
//       "Japan",
//       "Jordan",
//       "Kazakhstan",
//       "Kuwait",
//       "Kyrgyzstan",
//       "Lao People's Democratic Republic",
//       "Lebanon",
//       "Macao",
//       "Malaysia",
//       "Maldives",
//       "Mongolia",
//       "Myanmar",
//       "N. Korea",
//       "Nepal",
//       "Oman",
//       "Pakistan",
//       "Palestine",
//       "Philippines",
//       "Qatar",
//       "S. Korea",
//       "Saudi Arabia",
//       "Singapore",
//       "Sri Lanka",
//       "Syrian Arab Republic",
//       "Taiwan",
//       "Tajikistan",
//       "Thailand",
//       "Timor-Leste",
//       "Turkey",
//       "UAE",
//       "Uzbekistan",
//       "Vietnam",
//       "Yemen",
//       "Albania",
//       "Andorra",
//       "Austria",
//       "Belarus",
//       "Belgium",
//       "Bosnia",
//       "Bulgaria",
//       "Channel Islands",
//       "Croatia",
//       "Czechia",
//       "Denmark",
//       "Estonia",
//       "Faroe Islands",
//       "Finland",
//       "France",
//       "Germany",
//       "Gibraltar",
//       "Greece",
//       "Holy See (Vatican City State)",
//       "Hungary",
//       "Iceland",
//       "Ireland",
//       "Isle of Man",
//       "Italy",
//       "Latvia",
//       "Liechtenstein",
//       "Lithuania",
//       "Luxembourg",
//       "Macedonia",
//       "Malta",
//       "Moldova",
//       "Monaco",
//       "Montenegro",
//       "Netherlands",
//       "Norway",
//       "Poland",
//       "Portugal",
//       "Romania",
//       "Russia",
//       "San Marino",
//       "Serbia",
//       "Slovakia",
//       "Slovenia",
//       "Spain",
//       "Sweden",
//       "Switzerland",
//       "UK",
//       "Ukraine",
//     ],
//   },
//   {
//     continent: "North America",
//     countries: [
//       "Anguilla",
//       "Antigua and Barbuda",
//       "Aruba",
//       "Bahamas",
//       "Barbados",
//       "Belize",
//       "Bermuda",
//       "British Virgin Islands",
//       "Canada",
//       "Caribbean Netherlands",
//       "Cayman Islands",
//       "Costa Rica",
//       "Cuba",
//       "Curaçao",
//       "Dominica",
//       "Dominican Republic",
//       "El Salvador",
//       "Greenland",
//       "Grenada",
//       "Guadeloupe",
//       "Guatemala",
//       "Haiti",
//       "Honduras",
//       "Jamaica",
//       "Martinique",
//       "Mexico",
//       "Montserrat",
//       "Nicaragua",
//       "Panama",
//       "Saint Kitts and Nevis",
//       "Saint Lucia",
//       "Saint Martin",
//       "Saint Pierre Miquelon",
//       "Saint Vincent and the Grenadines",
//       "Sint Maarten",
//       "St. Barth",
//       "Trinidad and Tobago",
//       "Turks and Caicos Islands",
//       "USA",
//     ],
//   },
//   {
//     continent: "Asia",
//     countries: [
//       "Afghanistan",
//       "Armenia",
//       "Azerbaijan",
//       "Bahrain",
//       "Bangladesh",
//       "Bhutan",
//       "Brunei",
//       "Cambodia",
//       "China",
//       "Cyprus",
//       "Georgia",
//       "Hong Kong",
//       "India",
//       "Indonesia",
//       "Iran",
//       "Iraq",
//       "Israel",
//       "Japan",
//       "Jordan",
//       "Kazakhstan",
//       "Kuwait",
//       "Kyrgyzstan",
//       "Lao People's Democratic Republic",
//       "Lebanon",
//       "Macao",
//       "Malaysia",
//       "Maldives",
//       "Mongolia",
//       "Myanmar",
//       "N. Korea",
//       "Nepal",
//       "Oman",
//       "Pakistan",
//       "Palestine",
//       "Philippines",
//       "Qatar",
//       "S. Korea",
//       "Saudi Arabia",
//       "Singapore",
//       "Sri Lanka",
//       "Syrian Arab Republic",
//       "Taiwan",
//       "Tajikistan",
//       "Thailand",
//       "Timor-Leste",
//       "Turkey",
//       "UAE",
//       "Uzbekistan",
//       "Vietnam",
//       "Yemen",
//     ],
//   },
//   {
//     continent: "Europe",
//     countries: [
//       "Albania",
//       "Andorra",
//       "Austria",
//       "Belarus",
//       "Belgium",
//       "Bosnia",
//       "Bulgaria",
//       "Channel Islands",
//       "Croatia",
//       "Czechia",
//       "Denmark",
//       "Estonia",
//       "Faroe Islands",
//       "Finland",
//       "France",
//       "Germany",
//       "Gibraltar",
//       "Greece",
//       "Holy See (Vatican City State)",
//       "Hungary",
//       "Iceland",
//       "Ireland",
//       "Isle of Man",
//       "Italy",
//       "Latvia",
//       "Liechtenstein",
//       "Lithuania",
//       "Luxembourg",
//       "Macedonia",
//       "Malta",
//       "Moldova",
//       "Monaco",
//       "Montenegro",
//       "Netherlands",
//       "Norway",
//       "Poland",
//       "Portugal",
//       "Romania",
//       "Russia",
//       "San Marino",
//       "Serbia",
//       "Slovakia",
//       "Slovenia",
//       "Spain",
//       "Sweden",
//       "Switzerland",
//       "UK",
//       "Ukraine",
//     ],
//   },
//   {
//     continent: "South America",
//     countries: [
//       "Argentina",
//       "Bolivia",
//       "Brazil",
//       "Chile",
//       "Colombia",
//       "Ecuador",
//       "Falkland Islands (Malvinas)",
//       "French Guiana",
//       "Guyana",
//       "Paraguay",
//       "Peru",
//       "Suriname",
//       "Uruguay",
//       "Venezuela",
//     ],
//   },
//   {
//     continent: "Australia-Oceania",
//     countries: [
//       "Australia",
//       "Cook Islands",
//       "Fiji",
//       "French Polynesia",
//       "Kiribati",
//       "Marshall Islands",
//       "Micronesia",
//       "Nauru",
//       "New Caledonia",
//       "New Zealand",
//       "Niue",
//       "Palau",
//       "Papua New Guinea",
//       "Samoa",
//       "Solomon Islands",
//       "Tokelau",
//       "Tonga",
//       "Tuvalu",
//       "Vanuatu",
//       "Wallis and Futuna",
//     ],
//   },
//   {
//     continent: "Africa",
//     countries: [
//       "Algeria",
//       "Angola",
//       "Benin",
//       "Botswana",
//       "Burkina Faso",
//       "Burundi",
//       "Cabo Verde",
//       "Cameroon",
//       "Central African Republic",
//       "Chad",
//       "Comoros",
//       "Congo",
//       "Côte d'Ivoire",
//       "DRC",
//       "Djibouti",
//       "Egypt",
//       "Equatorial Guinea",
//       "Eritrea",
//       "Ethiopia",
//       "Gabon",
//       "Gambia",
//       "Ghana",
//       "Guinea",
//       "Guinea-Bissau",
//       "Kenya",
//       "Lesotho",
//       "Liberia",
//       "Libyan Arab Jamahiriya",
//       "Madagascar",
//       "Malawi",
//       "Mali",
//       "Mauritania",
//       "Mauritius",
//       "Mayotte",
//       "Morocco",
//       "Mozambique",
//       "Namibia",
//       "Niger",
//       "Nigeria",
//       "Rwanda",
//       "Réunion",
//       "Saint Helena",
//       "Sao Tome and Principe",
//       "Senegal",
//       "Seychelles",
//       "Sierra Leone",
//       "Somalia",
//       "South Africa",
//       "South Sudan",
//       "Sudan",
//       "Swaziland",
//       "Tanzania",
//       "Togo",
//       "Tunisia",
//       "Uganda",
//       "Western Sahara",
//       "Zambia",
//       "Zimbabwe",
//     ],
//   },
// ];

export const monthList: string[] = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export function getDate(month: number, year: number) {
  const dateList: string[] = [];

  function genDate31() {
    for (let i = 1; i <= 31; i++) {
      const eachDate = `${month}/${i}/${year}`;
      dateList.push(eachDate);
    }
  }

  function genDate30() {
    for (let i = 1; i <= 30; i++) {
      const eachDate = `${month}/${i}/${year}`;
      dateList.push(eachDate);
    }
  }

  function genDate28() {
    for (let i = 1; i <= 28; i++) {
      const eachDate = `${month}/${i}/${year}`;
      dateList.push(eachDate);
    }
  }

  if (
    month === 1 ||
    month === 3 ||
    month === 5 ||
    month === 7 ||
    month === 8 ||
    month === 10 ||
    month === 12
  )
    genDate31();
  else if (month === 4 || month === 6 || month === 9 || month === 11)
    genDate30();
  else if (month === 2) genDate28();

  return dateList;
}
